### ISSUE TITLE
Add "concepts" to kiwi.toml

### ISSUE THREAD

**Issue by FredrikNoren** [KiwiOrg/Kiwi#59]

**Comment by philpax** [comment]
Just sketching out some thoughts for tomorrow:
- A concept is a list of components that, when used together, result in some behaviour (likely driven by a host system or the module)
- These components can have default values
- The macro will generate a function to create a `Components` containing all of the specified components with their defaults; all components that don't have defaults will be made into parameters
- The macro will generate a function to check if a specific entity abides by a concept
- For now, you will *only* be able to use components that you define. 
  - The first extension will be to support core components; I'm not really sure how to do this, given that the macro won't have access to `kiwi_api`'s `kiwi.toml`. Could copy it in or see if it's possible to pass it in somehow.
  - Once #23 is in, it should hopefully be a fairly natural extension to support that, too
- You can extend other concepts, but the same caveat about being in the same `toml` applies
- These are purely for convenience and do not exist in the ECS proper - they're like TypeScript interfaces

Here's a rough idea of how that might look:
```toml
[concepts.transformable]
name = "Transformable"
description = "Can be translated, rotated and scaled."
components = {
  "core::transform::translation" = [0, 0, 0],
  "core::transform::rotation" = [0, 0, 0, 1],
  "core::transform::scale" = [1, 1, 1],
}

[concepts.sphere]
name = "Sphere"
description = "A primitive sphere."
extends = ["transformable"]
components = {
  "core::primitives::sphere_radius": 0.5,
  "core::primitives::sphere_sectors": 36,
  "core::primitives::sphere_stacks": 18
}

[concepts.colored_sphere]
name = "Colored Sphere"
description = "A sphere with some color!"
extends = ["sphere"]
components = { "core::rendering::color" = {} }
```

generates the following:
```rust
/// Makes a Transformable (Can be translated, rotated and scaled.)
pub fn make_transformable() -> Components {
  Components::new()
    .with(translation(), vec3(0.0, 0.0, 0.0))
    .with(rotation(), quat(0.0, 0.0, 0.0, 1.0))
    .with(scale(), vec3(1.0, 1.0, 1.0))
}

/// Checks if the entity is a Transformable (Can be translated, rotated and scaled.)
pub fn is_transformable(id: EntityId) -> bool {
  entity::has_components(id, [translation(), rotation(), scale()]);
}

/// Makes a Sphere (A primitive sphere.)
pub fn make_sphere() -> Components {
  make_transformable()
    .with(sphere_radius(), 0.5)
    .with(sphere_sectors(), 36)
    .with(sphere_stacks(), 18)
}

/// Checks if the entity is a Sphere (A primitive sphere.)
pub fn is_sphere(id: EntityId) -> bool {
  is_transformable(id) && entity::has_components(id, [sphere_radius(), sphere_sectors(), sphere_stacks()]);
}

/// Makes a Colored Sphere (A sphere with some color!)
pub fn make_colored_sphere(color_value: Vec4) -> Components {
  make_sphere()
    .with(color(), color_value)
}

/// Checks if the entity is a Colored Sphere (A sphere with some color!)
pub fn is_colored_sphere(id: EntityId) -> bool {
  is_sphere(id) && entity::has_components(id, [color()]);
}
```
